name: Create Release and Upload Assets

on:
  push:
    tags:
      - 'v*' # Triggers the workflow on version tags like v1.0, v2.1.3, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create releases and upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out your repository's code

      - name: Get release version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        # This extracts the tag name (e.g., v1.0.0) and makes it available as env.VERSION

      - name: Create project archive (excluding README and LICENSE)
        # This command zips all files in the current directory (.)
        # -x excludes specified files/patterns.
        # The archive will be named like 'ydtkelime-v1.0.0.zip'
        run: zip -r ydtkelime-${{ env.VERSION }}.zip . -x README.md -x LICENSE

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2 # A popular action for creating releases
        with:
          files: ydtkelime-${{ env.VERSION }}.zip # The archive to upload
          # The tag_name and release name will be automatically derived from the pushed tag
          # You can customize the release name and body if needed:
          # name: Release ${{ env.VERSION }}
          # body: |
          #   This is the official release for version ${{ env.VERSION }}.
          #   See what's new:
          #   - Feature A
          #   - Bugfix B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is automatically provided by GitHub
